version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "@types/node"
        versions: ">= 21"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
