// SW
export const sw: Record<number, string> = {
  0x00: 'SW_LID' /* set = lid shut */,
  0x01: 'SW_TABLET_MODE' /* set = tablet mode */,
  0x02: 'SW_HEADPHONE_INSERT' /* set = inserted */,
  0x03: 'SW_RFKILL_ALL' /* rfkill master switch, type "any" */,
  0x04: 'SW_MICROPHONE_INSERT' /* set = inserted */,
  0x05: 'SW_DOCK' /* set = plugged into dock */,
  0x06: 'SW_LINEOUT_INSERT' /* set = inserted */,
  0x07: 'SW_JACK_PHYSICAL_INSERT' /* set = mechanical switch set */,
  0x08: 'SW_VIDEOOUT_INSERT' /* set = inserted */,
  0x09: 'SW_CAMERA_LENS_COVER' /* set = lens covered */,
  0x0a: 'SW_KEYPAD_SLIDE' /* set = keypad slide out */,
  0x0b: 'SW_FRONT_PROXIMITY' /* set = front proximity sensor active */,
  0x0c: 'SW_ROTATE_LOCK' /* set = rotate locked/disabled */,
  0x0d: 'SW_LINEIN_INSERT' /* set = inserted */,
  0x0e: 'SW_MUTE_DEVICE' /* set = device disabled */,
  0x0f: 'SW_PEN_INSERTED' /* set = pen inserted */,
  0x10: 'SW_MAX',
}
